ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - sharp
  - unrs-resolver

overrides:
  flatted@<3.4.0: '>=3.4.0'
  flatted@<=3.4.1: '>=3.4.2'
  next@>=16.0.0-beta.0 <16.1.7: '>=16.1.7'
  next@>=16.0.1 <16.1.7: '>=16.1.7'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  svgo@>=3.0.0 <3.3.3: '>=3.3.3'
